services:
  mts_db:
    image: postgres:15
    container_name: mts_db
    environment:
      POSTGRES_DB: mts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: postgres -c max_prepared_transactions=100
    volumes:
      - mts_db_data:/var/lib/postgresql/data

  billing_db:
    image: postgres:15
    container_name: billing_db
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    command: postgres -c max_prepared_transactions=100
    volumes:
      - billing_db_data:/var/lib/postgresql/data

volumes:
  mts_db_data:
  billing_db_data: