org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.parallel=false
org.gradle.vfs.watch=false
org.gradle.jvmargs=-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=256m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
app.taiga.base-url=http://localhost:9000
app.taiga.api-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc5MzU4NDgwLCJqdGkiOiJmMTU1NTVlOWU5OTM0MTQ3OWQ2N2M1MDU3Y2MyODRjOSIsInVzZXJfaWQiOjZ9.zAGT-zgpHs-4OVMMwcSMYBpz-xIpTNoI_N1Ob5yzJuI
app.taiga.project-id=1
